---
- name: install python from apt
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  become: yes
  with_items:
    - python-dev
    - libffi-dev
    - libssl-dev
    - python-pip
    - python-setuptools

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - tox
    - pymongo

